'use strict';
(() => {
  const S=window.SleepRoadSystems,{Renderer,compose,makeBox,makeCylinder,makeCone,makeSphere,DEG,UI,COLORS,MAX_UPGRADE,MAX_CROWD,clamp,lerp,TAU,loadSave,saveGame,RNG,AudioEngine,CrowdBatch,gateLabel}=S;
  class SleepRoad3D{
    constructor(){
      this.save=loadSave();this.audio=new AudioEngine(this.save.sound);this.state='menu';this.level=this.save.level;this.w=innerWidth;this.h=innerHeight;this.dpr=1;this.time=0;this.last=performance.now();
      this.travel=0;this.levelLength=280;this.baseSpeed=9.7;this.speed=this.baseSpeed;this.playerX=0;this.targetX=0;this.playerZ=1.6;this.playerCount=this.startCount();this.visualCount=this.playerCount;this.objects=[];this.knockouts=[];this.levelMoons=0;this.finishMultiplier=1;this.finishProgress=0;this.finishTargetStep=0;this.finishRewarded=false;this.battleEnemy=null;this.battleTimer=0;this.pointer={down:false,startX:0,startPlayerX:0};this.keys=new Set();this.toastTimer=0;this.resultTimer=0;this.labels=[];this.labelCursor=0;this.shake=0;this.flash=0;this.shield=0;this.dodgedObstacles=0;this.missionRewarded=false;this.mission=this.createMission(this.level);
      try{this.renderer=new Renderer(UI.canvas);}catch(err){UI.fatal.classList.remove('hidden');throw err;}
      this.meshes={box:this.renderer.createMesh(makeBox()),cylinder:this.renderer.createMesh(makeCylinder(16)),cone:this.renderer.createMesh(makeCone(16)),sphere:this.renderer.createMesh(makeSphere(10,16))};this.crowdBatch=new CrowdBatch(this.renderer,this.meshes);this.bind();this.resize();this.generateLevel(this.level);this.refreshUI();requestAnimationFrame(t=>this.loop(t));window.__sleepRoad=this;
    }
    startCount(){return 8+this.save.upgrades.crowd*5;} magnetRadius(){return .82+this.save.upgrades.magnet*.13;} incomeScale(){return 1+this.save.upgrades.income*.12;} upgradeCost(type){const base=type==='crowd'?40:type==='magnet'?55:70,lv=this.save.upgrades[type];return Math.round(base*Math.pow(1.46,lv)/5)*5;}
    bind(){
      addEventListener('resize',()=>this.resize(),{passive:true});addEventListener('orientationchange',()=>setTimeout(()=>this.resize(),120),{passive:true});document.addEventListener('visibilitychange',()=>{this.last=performance.now();});
      UI.canvas.addEventListener('pointerdown',e=>{if(this.state!=='running')return;this.pointer.down=true;this.pointer.startX=e.clientX;this.pointer.startPlayerX=this.targetX;try{UI.canvas.setPointerCapture(e.pointerId)}catch{}});
      UI.canvas.addEventListener('pointermove',e=>{if(!this.pointer.down||this.state!=='running')return;const dx=e.clientX-this.pointer.startX;this.targetX=clamp(this.pointer.startPlayerX+dx/Math.max(260,this.w)*10.2,-4.3,4.3);});const up=()=>{this.pointer.down=false};UI.canvas.addEventListener('pointerup',up);UI.canvas.addEventListener('pointercancel',up);
      addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','KeyA','KeyD'].includes(e.code))e.preventDefault();if(e.code==='Escape'&&this.state!=='menu'){this.returnToMenu();return;}this.keys.add(e.code);});addEventListener('keyup',e=>this.keys.delete(e.code));
      UI.playBtn.addEventListener('click',()=>{this.audio.ensure();this.startLevel(this.save.level)});UI.nextBtn.addEventListener('click',()=>{this.audio.ensure();this.startLevel(this.save.level)});UI.retryBtn.addEventListener('click',()=>{this.audio.ensure();this.startLevel(this.level)});
      UI.exitBtn.addEventListener('click',()=>this.returnToMenu());UI.resultMenuBtn.addEventListener('click',()=>this.returnToMenu());
      const toggle=()=>{this.save.sound=!this.save.sound;this.audio.enabled=this.save.sound;if(this.save.sound)this.audio.ensure();saveGame(this.save);this.refreshUI();};UI.soundBtn.addEventListener('click',toggle);UI.menuSoundBtn.addEventListener('click',toggle);UI.upgradeCrowd.addEventListener('click',()=>this.buyUpgrade('crowd'));UI.upgradeMagnet.addEventListener('click',()=>this.buyUpgrade('magnet'));UI.upgradeIncome.addEventListener('click',()=>this.buyUpgrade('income'));
    }
    resize(){this.w=Math.max(320,innerWidth);this.h=Math.max(500,innerHeight);this.dpr=Math.min(1.7,Math.max(1,devicePixelRatio||1));this.renderer.resize(this.w,this.h,this.dpr);}
    refreshUI(){UI.menuMoonValue.textContent=this.save.moons.toLocaleString('ru-RU');UI.moonValue.textContent=this.save.moons.toLocaleString('ru-RU');UI.menuLevelValue.textContent=this.save.level;UI.soundBtn.textContent=UI.menuSoundBtn.textContent=this.save.sound?'🔊':'🔇';UI.crowdUpgradeText.textContent=`Старт: ${this.startCount()}`;UI.magnetUpgradeText.textContent=`Радиус: ${(1+this.save.upgrades.magnet*.13).toFixed(1)}×`;UI.incomeUpgradeText.textContent=`Бонус: +${Math.round((this.incomeScale()-1)*100)}%`;this.updateUpgrade('crowd',UI.upgradeCrowd,UI.crowdUpgradeCost);this.updateUpgrade('magnet',UI.upgradeMagnet,UI.magnetUpgradeCost);this.updateUpgrade('income',UI.upgradeIncome,UI.incomeUpgradeCost);this.updateMissionUI();}
    createMission(level){const kind=['moon','dodge','crowd'][(Math.max(1,level)-1)%3];if(kind==='moon'){const target=18+Math.min(28,level*2);return{kind,target,reward:24+level*3,title:`Собери ${target} лун`};}if(kind==='dodge'){const target=2+Math.min(4,Math.floor(level/5));return{kind,target,reward:32+level*3,title:`Пройди ${target} ловушки без потерь`};}const target=55+Math.min(260,level*7);return{kind,target,reward:38+level*3,title:`Доведи ${target} человек до финиша`};}
    missionProgress(){if(this.mission.kind==='moon')return this.levelMoons;if(this.mission.kind==='dodge')return this.dodgedObstacles;return this.playerCount;}
    missionComplete(){return this.mission.kind==='crowd'?(this.state==='finish'||this.state==='complete')&&this.playerCount>=this.mission.target:this.missionProgress()>=this.mission.target;}
    updateMissionUI(){if(!this.mission)return;const progress=Math.min(this.mission.target,this.missionProgress());UI.menuMissionText.textContent=this.mission.title;UI.menuMissionReward.textContent=`Награда: ☾ ${this.mission.reward}`;UI.missionHudText.textContent=`${this.mission.title} · ${progress}/${this.mission.target}`;UI.missionFill.style.width=`${clamp(progress/this.mission.target*100,0,100)}%`;UI.shieldHud.classList.toggle('hidden',this.shield<=0);}
    updateUpgrade(type,button,costEl){const max=this.save.upgrades[type]>=MAX_UPGRADE[type],cost=max?0:this.upgradeCost(type);costEl.textContent=max?'MAX':cost;button.classList.toggle('maxed',max);button.classList.toggle('can-buy',!max&&this.save.moons>=cost);}
    buyUpgrade(type){if(this.save.upgrades[type]>=MAX_UPGRADE[type])return;const cost=this.upgradeCost(type);if(this.save.moons<cost){this.toast('Не хватает лун');this.audio.bad();return;}this.save.moons-=cost;this.save.upgrades[type]++;saveGame(this.save);this.refreshUI();this.audio.good();if(type==='crowd'&&this.state==='menu')this.playerCount=this.visualCount=this.startCount();}
    returnToMenu(){clearTimeout(this.resultTimer);this.resultTimer=0;this.state='menu';this.travel=0;this.pointer.down=false;this.keys.clear();this.knockouts=[];this.battleEnemy=null;this.playerX=this.targetX=0;this.playerCount=this.visualCount=this.startCount();this.shield=0;this.dodgedObstacles=0;this.missionRewarded=false;this.level=this.save.level;this.mission=this.createMission(this.level);this.generateLevel(this.level);this.speed=0;UI.hud.classList.add('hidden');UI.result.classList.add('hidden');UI.menu.classList.remove('hidden');UI.toast.classList.add('hidden');this.refreshUI();}
    startLevel(level){clearTimeout(this.resultTimer);this.resultTimer=0;this.level=Math.max(1,Math.floor(level));this.travel=0;this.playerX=this.targetX=0;this.playerCount=this.visualCount=this.startCount();this.levelMoons=0;this.finishMultiplier=1;this.finishProgress=0;this.finishTargetStep=0;this.finishRewarded=false;this.battleEnemy=null;this.knockouts=[];this.shake=0;this.flash=0;this.shield=0;this.dodgedObstacles=0;this.missionRewarded=false;this.mission=this.createMission(this.level);this.generateLevel(this.level);this.state='running';UI.menu.classList.add('hidden');UI.result.classList.add('hidden');UI.hud.classList.remove('hidden');UI.progressFill.style.width='0%';UI.moonValue.textContent=this.save.moons;this.setCrowdCount(this.playerCount,false);this.updateMissionUI();}
    generateLevel(level){const rng=new RNG(0x51eed00d+level*7919),difficulty=clamp((level-1)/28,0,1),sections=11+Math.min(9,Math.floor(level/3)),spacing=48-2*difficulty;this.baseSpeed=8.8+1.15*difficulty;this.speed=this.baseSpeed;this.objects=[];let d=42;for(let i=0;i<sections;i++){this.objects.push(this.makeGate(rng,d,i,level));this.addMoons(rng,d+7,i);const hasEnemy=i>=2&&(i%3===2||rng.next()<.20);if(hasEnemy){const count=Math.max(8,Math.round((12+level*.72+i*2.05)*rng.range(.72,1.02)));this.objects.push({type:'enemy',distance:d+33,count,maxCount:count,boss:level%5===0&&i===sections-2,processed:false,phase:rng.range(0,TAU)});}else if(i>0&&rng.next()<.92)this.objects.push(this.makeObstacle(rng,d+28,difficulty,i));if(i>0&&i%4===1)this.objects.push({type:'powerup',kind:'shield',distance:d-7,x:rng.pick([-3,0,3]),processed:false,spin:rng.range(0,TAU)});d+=spacing+rng.range(-2.5,2.5);}this.levelLength=d+52;this.objects.push({type:'finish',distance:this.levelLength,processed:false});this.objects.sort((a,b)=>a.distance-b.distance);}
    makeGate(rng,d,i,level){let a=i===0?{op:'mul',value:2}:(rng.next()<.52?{op:'mul',value:rng.pick([2,2,3])}:{op:'add',value:rng.int(12,26+level)}),b=i===0?{op:'add',value:18+level}:(rng.next()<.54?{op:'add',value:rng.int(14,36+level)}:{op:'mul',value:rng.pick([2,2,3])});if(i>2&&rng.next()<.24)b=rng.next()<.68?{op:'sub',value:rng.int(5,13+Math.floor(level*.4))}:{op:'div',value:2};if(rng.next()<.5)[a,b]=[b,a];return{type:'gate',distance:d,left:a,right:b,processed:false};}
    makeObstacle(rng,d,diff){
      const pool=diff<.25?['spinner','spikes','poles','barrier']:diff<.66?['spinner','spikes','poles','barrier','saw','pusher','hammer']:['spinner','spikes','saw','pusher','poles','barrier','hammer','laser','roller'],kind=rng.pick(pool);
      if(kind==='spinner')return{type:'obstacle',kind,distance:d,processed:false,phase:rng.range(0,TAU),speed:rng.range(.85,1.2)};
      if(kind==='saw')return{type:'obstacle',kind,distance:d,processed:false,baseX:rng.pick([-2.5,2.5]),range:rng.range(1.3,2),speed:rng.range(.8,1.15),phase:rng.range(0,TAU)};
      if(kind==='pusher')return{type:'obstacle',kind,distance:d,processed:false,side:rng.next()<.5?-1:1,speed:rng.range(.8,1.1),phase:rng.range(0,TAU)};
      if(kind==='hammer')return{type:'obstacle',kind,distance:d,processed:false,phase:rng.range(0,TAU),speed:rng.range(.9,1.25),range:rng.range(.9,1.35)};
      if(kind==='roller')return{type:'obstacle',kind,distance:d,processed:false,phase:rng.range(0,TAU),speed:rng.range(.8,1.15)};
      if(kind==='laser')return{type:'obstacle',kind,distance:d,processed:false,safeX:rng.pick([-3.05,0,3.05])};
      if(kind==='spikes'){const safeX=rng.pick([-3.1,0,3.1]),spikes=[],target=rng.int(14,20);for(let tries=0;tries<140&&spikes.length<target;tries++){const x=rng.range(-4.8,4.8),z=rng.range(-1.45,1.25);if(Math.abs(x-safeX)<1.35||spikes.some(p=>Math.hypot(p.x-x,p.z-z)<.66))continue;spikes.push({x,z});}return{type:'obstacle',kind,distance:d,processed:false,safeX,spikes};}
      const safeX=rng.pick([-3.15,0,3.15]),blockXs=[],count=kind==='barrier'?rng.int(4,6):4;for(let tries=0;tries<70&&blockXs.length<count;tries++){const x=rng.range(-4.6,4.6);if(Math.abs(x-safeX)<1.35||blockXs.some(px=>Math.abs(px-x)<1.05))continue;blockXs.push(x);}return{type:'obstacle',kind,distance:d,processed:false,poleXs:blockXs,safeX};
    }
    addMoons(rng,d,section){const pattern=rng.pick(['line','zigzag','arc','cluster']),count=rng.int(5,9);for(let i=0;i<count;i++){let x=0;if(pattern==='line')x=rng.pick([-3.1,0,3.1]);if(pattern==='zigzag')x=i%2?2.9:-2.9;if(pattern==='arc')x=Math.sin((i/Math.max(1,count-1))*Math.PI-Math.PI/2)*3.3;if(pattern==='cluster')x=rng.range(-3.4,3.4);this.objects.push({type:'moon',distance:d+i*2.2,x,processed:false,bonus:section>3&&rng.next()<.08,spin:rng.range(0,TAU)});}}
    loop(now){const dt=Math.min(.035,Math.max(0,(now-this.last)/1000));this.last=now;this.time+=dt;this.update(dt);this.render();requestAnimationFrame(t=>this.loop(t));}
    update(dt){this.shake=Math.max(0,this.shake-dt*16);this.flash=Math.max(0,this.flash-dt*2.4);this.updateKnockouts(dt);if(this.state==='menu'){this.visualCount=lerp(this.visualCount,this.startCount(),1-Math.pow(.001,dt));return;}if(this.state==='finish'){this.updateFinish(dt);return;}if(this.state==='battle'){this.updateBattle(dt);return;}if(this.state!=='running')return;let move=0;if(this.keys.has('ArrowLeft')||this.keys.has('KeyA'))move--;if(this.keys.has('ArrowRight')||this.keys.has('KeyD'))move++;if(move)this.targetX=clamp(this.targetX+move*dt*6.8,-4.3,4.3);this.playerX=lerp(this.playerX,this.targetX,1-Math.pow(.0006,dt));this.travel+=this.speed*dt;this.visualCount=lerp(this.visualCount,this.playerCount,1-Math.pow(.002,dt));UI.progressFill.style.width=`${clamp(this.travel/this.levelLength*100,0,100)}%`;for(const o of this.objects){if(o.processed)continue;const z=this.objectZ(o);if(o.type==='moon'||o.type==='powerup'){if(z>this.playerZ-1.2&&z<this.playerZ+2&&Math.abs(this.playerX-o.x)<(o.type==='moon'?this.magnetRadius()*1.4:1.05)){o.processed=true;o.type==='moon'?this.collectMoon(o):this.collectPowerup(o);}continue;}if(z<this.playerZ-.25||z>this.playerZ+1.15)continue;if(o.type==='gate'){o.processed=true;this.applyGate(this.playerX<0?o.left:o.right);}else if(o.type==='obstacle'){o.processed=true;this.hitObstacle(o);}else if(o.type==='enemy'){o.processed=true;this.beginBattle(o);break;}else if(o.type==='finish'){o.processed=true;this.beginFinish();break;}}if(this.playerCount<=0)this.fail();}
    objectZ(o){return-o.distance+this.travel;}
    applyGate(opt){const before=this.playerCount;let after=before;if(opt.op==='mul')after*=opt.value;else if(opt.op==='add')after+=opt.value;else if(opt.op==='sub')after-=opt.value;else after=Math.ceil(after/opt.value);after=clamp(Math.round(after),1,MAX_CROWD);this.playerCount=after;this.setCrowdCount(after,true);after>=before?this.audio.good():this.audio.bad();this.toast(`${gateLabel(opt)} → ${after}`);this.flash=.12;this.updateMissionUI();}
    collectMoon(o){const gain=Math.max(1,Math.round((o.bonus?5:1)*this.incomeScale()));this.levelMoons+=gain;this.save.moons+=gain;saveGame(this.save);UI.moonValue.textContent=this.save.moons;this.audio.coin();this.updateMissionUI();}
    collectPowerup(){this.shield=1;this.audio.good();this.flash=.12;this.toast('ЩИТ ПОЛУЧЕН — одно столкновение не страшно',1200);this.updateMissionUI();}
    obstacleHits(o,formation){let hits=0;for(const q of formation){const x=this.playerX+q.x,crossingTime=this.time+q.z/Math.max(1,this.baseSpeed),angle=crossingTime*(o.speed||1)+(o.phase||0);if(o.kind==='spinner'){const bars=[[angle,3.95,.40],[angle+Math.PI/2,2.95,.38]];if(bars.some(([a,half,width])=>Math.abs(Math.sin(a)*x)<width&&Math.abs(Math.cos(a)*x)<half))hits++;}else if(o.kind==='saw'){const sx=o.baseX+Math.sin(angle)*o.range;if(Math.abs(x-sx)<.84)hits++;}else if(o.kind==='pusher'){const reach=.65+(Math.sin(angle)*.5+.5)*2.55;if(o.side<0?x<-5.05+reach:x>5.05-reach)hits++;}else if(o.kind==='spikes'){if(o.spikes?o.spikes.some(p=>Math.hypot(x-p.x,q.z-p.z)<.48):Math.abs(x-o.safeX)>1.02)hits++;}else if(o.kind==='poles'||o.kind==='barrier'){if(o.poleXs.some(px=>Math.abs(x-px)<(o.kind==='barrier'?.60:.47)))hits++;}else if(o.kind==='hammer'){const centers=[-2.7+Math.sin(angle)*o.range,2.7-Math.sin(angle)*o.range];if(centers.some(cx=>Math.abs(x-cx)<.72))hits++;}else if(o.kind==='roller'){const centers=[Math.sin(angle)*3.15,-Math.sin(angle*.83+1.2)*3.0];if(centers.some(cx=>Math.abs(x-cx)<.70))hits++;}else if(o.kind==='laser'){if(Math.abs(x-o.safeX)>1.05)hits++;}}return hits;}
    hitObstacle(o){const formation=this.crowdBatch.formation(this.playerCount),hits=this.obstacleHits(o,formation);if(hits<=0){this.dodgedObstacles++;this.toast('ИДЕАЛЬНЫЙ МАНЁВР!',650);this.updateMissionUI();return;}if(this.shield>0){this.shield=0;this.audio.good();this.shake=4;this.flash=.18;this.toast('ЩИТ СПАС ТОЛПУ!',1000);this.updateMissionUI();return;}const scaledHits=Math.ceil(hits*this.playerCount/formation.length),maxLoss=Math.max(1,Math.ceil(this.playerCount*.72)),loss=clamp(scaledHits,1,maxLoss);this.spawnKnockouts(loss);this.playerCount=Math.max(0,this.playerCount-loss);this.visualCount=Math.min(this.visualCount,this.playerCount+Math.min(loss,12));this.setCrowdCount(this.playerCount,true);this.audio.hit();this.shake=12;this.flash=.31;this.toast(`ПОТЕРЯНО: ${loss}`,1050);this.updateMissionUI();}
    spawnKnockouts(loss){const f=this.crowdBatch.formation(Math.max(loss,4));for(let i=0;i<Math.min(loss,32);i++){const q=f[i%f.length],side=Math.sign(q.x)||((i%2)*2-1);this.knockouts.push({x:this.playerX+q.x,z:this.playerZ+q.z*.24,y:.55,vx:side*(1.8+Math.random()*3.3),vy:3.8+Math.random()*2.8,vz:(Math.random()-.5)*4.2,spin:(Math.random()-.5)*8,life:1.15});}}
    updateKnockouts(dt){for(const k of this.knockouts){k.life-=dt;k.x+=k.vx*dt;k.y+=k.vy*dt;k.z+=k.vz*dt;k.vy-=8.8*dt;}this.knockouts=this.knockouts.filter(k=>k.life>0);}
    beginBattle(enemy){this.state='battle';this.battleEnemy=enemy;enemy.battleZ=this.objectZ(enemy);this.battleTimer=0;this.speed=0;this.toast(`${this.playerCount} против ${enemy.count}`);}
    updateBattle(dt){const e=this.battleEnemy;if(!e){this.state='running';this.speed=this.baseSpeed;return;}this.battleTimer+=dt;while(this.battleTimer>=.045&&this.playerCount>0&&e.count>0){this.battleTimer-=.045;this.playerCount--;e.count--;if((this.playerCount+e.count)%5===0)this.audio.battle();}this.visualCount=lerp(this.visualCount,this.playerCount,1-Math.pow(.003,dt));this.setCrowdCount(this.playerCount,false);if(this.playerCount<=0){this.updateMissionUI();this.fail();return;}if(e.count<=0){this.battleEnemy=null;this.state='running';this.speed=this.baseSpeed;this.audio.good();this.toast(e.boss?'Босс побеждён!':'Толпа побеждена');this.updateMissionUI();}}
    beginFinish(){this.state='finish';this.speed=0;this.finishProgress=0;this.finishTargetStep=clamp(Math.floor(this.playerCount/14)+1,1,8);this.finishMultiplier=1+this.finishTargetStep*.35;this.updateMissionUI();this.audio.win();}
    updateFinish(dt){this.finishProgress=Math.min(1,this.finishProgress+dt/2.35);if(this.finishProgress>=1&&!this.finishRewarded){this.finishRewarded=true;const bonus=Math.max(1,Math.round(this.playerCount*this.finishMultiplier*.45*this.incomeScale())),missionBonus=this.missionComplete()?this.mission.reward:0;this.missionRewarded=missionBonus>0;this.levelMoons+=bonus+missionBonus;this.save.moons+=bonus+missionBonus;this.save.level=this.level+1;saveGame(this.save);UI.moonValue.textContent=this.save.moons;if(missionBonus)this.toast(`МИССИЯ ВЫПОЛНЕНА: +${missionBonus} ☾`,1300);this.updateMissionUI();this.resultTimer=setTimeout(()=>{this.resultTimer=0;if(this.state==='finish')this.showResult(true);},450);}}
    fail(){if(this.state==='failed'||this.state==='complete')return;this.state='failed';this.speed=0;this.audio.fail();this.showResult(false);}
    showResult(won){this.state=won?'complete':'failed';UI.hud.classList.add('hidden');UI.result.classList.remove('hidden');UI.resultBanner.textContent=won?'УРОВЕНЬ ПРОЙДЕН!':'ПОПРОБУЙ ЕЩЁ!';UI.resultBanner.style.background=won?'#65a83b':'#c75761';UI.resultKicker.textContent=won?'SLEEP ROAD · ФИНИШ':'SLEEP ROAD · НЕУДАЧА';UI.resultTitle.textContent=won?'Отличный забег':'Толпа закончилась';UI.resultCount.textContent=Math.max(0,this.playerCount);UI.resultMoons.textContent=`+${this.levelMoons}`;UI.resultMultiplier.textContent=won?`×${this.finishMultiplier.toFixed(2)}`:'×1.00';UI.resultMission.textContent=this.missionRewarded?`✓ Миссия выполнена · +${this.mission.reward} ☾`:`Миссия: ${Math.min(this.mission.target,this.missionProgress())}/${this.mission.target}`;UI.resultMission.style.background=this.missionRewarded?'#e8f7f3':'#f3eef0';UI.resultMission.style.color=this.missionRewarded?'#268677':'#8a6a73';UI.nextBtn.classList.toggle('hidden',!won);UI.retryBtn.classList.toggle('hidden',won);this.refreshUI();}
    setCrowdCount(v,pop){UI.crowdCount.textContent=Math.max(0,Math.round(v));if(pop){UI.crowdCount.classList.remove('pop');void UI.crowdCount.offsetWidth;UI.crowdCount.classList.add('pop');setTimeout(()=>UI.crowdCount.classList.remove('pop'),150);}}
    toast(text,ms=850){UI.toast.textContent=text;UI.toast.classList.remove('hidden');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>UI.toast.classList.add('hidden'),ms);}
  }
  window.SleepRoad3D=SleepRoad3D;
})();
