'use strict';
(() => {
  const { Renderer, compose, makeBox, makeCylinder, makeCone, makeSphere, DEG } = window.Mini3D;
  const $ = (id) => document.getElementById(id);
  const clamp = (v,a,b) => Math.max(a,Math.min(b,v));
  const lerp = (a,b,t) => a+(b-a)*t;
  const TAU = Math.PI*2;
  const UI = {
    canvas:$('game'),labels:$('worldLabels'),hud:$('hud'),menu:$('menu'),result:$('result'),fatal:$('fatal'),progressFill:$('progressFill'),moonValue:$('moonValue'),menuMoonValue:$('menuMoonValue'),crowdCount:$('crowdCount'),soundBtn:$('soundBtn'),menuSoundBtn:$('menuSoundBtn'),exitBtn:$('exitBtn'),resultMenuBtn:$('resultMenuBtn'),playBtn:$('playBtn'),nextBtn:$('nextBtn'),retryBtn:$('retryBtn'),menuLevelValue:$('menuLevelValue'),resultBanner:$('resultBanner'),resultKicker:$('resultKicker'),resultTitle:$('resultTitle'),resultCount:$('resultCount'),resultMoons:$('resultMoons'),resultMultiplier:$('resultMultiplier'),toast:$('toast'),upgradeCrowd:$('upgradeCrowd'),upgradeMagnet:$('upgradeMagnet'),upgradeIncome:$('upgradeIncome'),crowdUpgradeText:$('crowdUpgradeText'),magnetUpgradeText:$('magnetUpgradeText'),incomeUpgradeText:$('incomeUpgradeText'),crowdUpgradeCost:$('crowdUpgradeCost'),magnetUpgradeCost:$('magnetUpgradeCost'),incomeUpgradeCost:$('incomeUpgradeCost')
  };
  const COLORS={road:[.34,.37,.44],roadStripe:[.92,.92,.82],roadEdge:[.90,.92,.96],blue:[.20,.55,.96],blueLight:[.38,.72,1],red:[.93,.20,.25],orange:[1,.40,.13],teal:[.16,.75,.67],pink:[.90,.20,.43],purple:[.28,.23,.50],gold:[1,.72,.09],navy:[.08,.10,.20],gray:[.43,.46,.54],white:[.99,.99,1],grass:[.36,.68,.40],grassDark:[.24,.51,.31],island:[.30,.44,.66],islandTop:[.45,.66,.88],step0:[.22,.76,.91],step1:[.16,.50,.94],step2:[.35,.20,.91],step3:[.67,.12,.78]};
  const SAVE_KEY='sleep-road-save-v4',LEGACY_KEYS=['sleep-road-save-v2','sleep-road-save-v1'],DEFAULT_SAVE={level:1,moons:0,sound:true,upgrades:{crowd:0,magnet:0,income:0}},MAX_UPGRADE={crowd:24,magnet:10,income:10},MAX_CROWD=999,MAX_VISIBLE_CROWD=420;
  const safeNum=(v,f=0)=>{const n=Number(v);return Number.isFinite(n)?n:f;};
  function loadSave(){try{let raw=localStorage.getItem(SAVE_KEY);if(!raw){for(const k of LEGACY_KEYS){raw=localStorage.getItem(k);if(raw)break;}}if(!raw)return JSON.parse(JSON.stringify(DEFAULT_SAVE));const d=JSON.parse(raw),u=d.upgrades||{};return{level:Math.max(1,Math.floor(safeNum(d.level,1))),moons:Math.max(0,Math.floor(safeNum(d.moons??d.coins,0))),sound:d.sound!==false,upgrades:{crowd:clamp(Math.floor(safeNum(u.crowd,0)),0,MAX_UPGRADE.crowd),magnet:clamp(Math.floor(safeNum(u.magnet,0)),0,MAX_UPGRADE.magnet),income:clamp(Math.floor(safeNum(u.income,0)),0,MAX_UPGRADE.income)}};}catch{return JSON.parse(JSON.stringify(DEFAULT_SAVE));}}
  function saveGame(s){try{localStorage.setItem(SAVE_KEY,JSON.stringify(s));}catch{}}
  class RNG{constructor(seed){this.s=(seed>>>0)||1;}next(){this.s=(Math.imul(this.s,1664525)+1013904223)>>>0;return this.s/4294967296;}range(a,b){return a+(b-a)*this.next();}int(a,b){return Math.floor(this.range(a,b+1));}pick(a){return a[Math.floor(this.next()*a.length)];}}
  class AudioEngine{constructor(enabled){this.enabled=enabled;this.ac=null;this.master=null;}ensure(){if(!this.enabled)return false;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return false;if(!this.ac){this.ac=new AC();this.master=this.ac.createGain();this.master.gain.value=.105;this.master.connect(this.ac.destination);}if(this.ac.state==='suspended')this.ac.resume().catch(()=>{});return true;}tone(f,d=.08,type='sine',gain=.055,slide=1){if(!this.ensure())return;const t=this.ac.currentTime,o=this.ac.createOscillator(),g=this.ac.createGain();o.type=type;o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(Math.max(40,f*slide),t+d);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(gain,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+d+.03);}coin(){this.tone(930,.08,'sine',.05,1.22)}good(){this.tone(450,.07,'triangle',.055,1.45);setTimeout(()=>this.tone(720,.10,'sine',.045,1.18),50)}bad(){this.tone(185,.13,'sawtooth',.045,.68)}hit(){this.tone(115,.09,'square',.04,.55)}battle(){this.tone(155,.055,'square',.025,.8)}win(){this.tone(430,.12,'triangle',.06,1.35);setTimeout(()=>this.tone(650,.15,'triangle',.055,1.25),100);setTimeout(()=>this.tone(850,.22,'sine',.05,1.12),220)}fail(){this.tone(220,.28,'triangle',.055,.5)}}
  function flattenMatrices(list){const out=new Float32Array(list.length*16);for(let i=0;i<list.length;i++)out.set(list[i],i*16);return out;}
  class CrowdBatch{
    constructor(renderer,meshes){this.r=renderer;this.meshes=meshes;}
    metrics(count){const n=Math.max(1,Math.min(Math.round(count),MAX_VISIBLE_CROWD)),cols=Math.min(16,Math.max(3,Math.ceil(Math.sqrt(n*1.05)))),spacing=Math.min(.70,9.2/Math.max(1,cols-1)),rowGap=Math.min(.62,spacing*.86);return{n,cols,spacing,rowGap,depth:(Math.ceil(n/cols)-1)*rowGap};}
    formation(count){const{n,cols,spacing,rowGap}=this.metrics(count),rows=[];for(let i=0;i<n;i++){const row=Math.floor(i/cols),rowCount=Math.min(cols,n-row*cols),col=i%cols,stagger=row%2?spacing*.10:-spacing*.10;rows.push({x:(col-(rowCount-1)/2)*spacing+stagger,z:row*rowGap,index:i});}return rows;}
    draw(count,rootX,rootZ,color,time,opts={}){const f=this.formation(count),scale=opts.scale||1,baseY=opts.baseY||0,direction=opts.direction||1,parts={shadow:[],head:[],hair:[],le:[],re:[],body:[],hip:[],la:[],ra:[],ll:[],rl:[],ls:[],rs:[]},cols={shadow:[],head:[],hair:[],le:[],re:[],body:[],hip:[],la:[],ra:[],ll:[],rl:[],ls:[],rs:[]},skin=[[1,.73,.54],[.72,.43,.29],[.94,.61,.42],[.48,.29,.22]],hair=[[.10,.07,.06],[.25,.13,.07],[.05,.04,.04],[.52,.30,.08]],enemy=opts.enemy===true;for(const q of f){const phase=time*8.3+q.index*.71,swing=Math.sin(phase)*.46,bob=Math.abs(Math.sin(phase))*.05,x=rootX+q.x*scale,z=rootZ+q.z*direction*scale,y=baseY+bob,skinColor=skin[q.index%skin.length],hairColor=hair[(q.index*3)%hair.length],shade=.90+(q.index%4)*.03,shirt=enemy?[Math.min(1,color[0]*shade),color[1]*shade,color[2]*shade]:[Math.min(1,color[0]*shade),Math.min(1,color[1]*shade),Math.min(1,color[2]*shade)],trouser=enemy?[.23,.08,.11]:[.07,.18,.37],hairScale=q.index%5===0?.43:.51;parts.shadow.push(compose(x,baseY+.018,z,0,0,0,.58*scale,.025,.40*scale));parts.head.push(compose(x,y+1.69*scale,z,0,0,0,.51*scale,.55*scale,.51*scale));parts.hair.push(compose(x,y+1.88*scale,z+.015*direction,0,0,0,hairScale*scale,.19*scale,hairScale*scale));parts.le.push(compose(x-.095*scale,y+1.72*scale,z-.247*direction*scale,0,0,0,.070*scale,.082*scale,.050*scale));parts.re.push(compose(x+.095*scale,y+1.72*scale,z-.247*direction*scale,0,0,0,.070*scale,.082*scale,.050*scale));parts.body.push(compose(x,y+1.07*scale,z,0,0,0,.48*scale,.72*scale,.34*scale));parts.hip.push(compose(x,y+.72*scale,z,0,0,0,.45*scale,.22*scale,.32*scale));parts.la.push(compose(x-.31*scale,y+1.08*scale,z,swing*.52,0,-.20,.13*scale,.55*scale,.13*scale));parts.ra.push(compose(x+.31*scale,y+1.08*scale,z,-swing*.52,0,.20,.13*scale,.55*scale,.13*scale));parts.ll.push(compose(x-.145*scale,y+.40*scale,z,-swing*.72,0,0,.15*scale,.65*scale,.15*scale));parts.rl.push(compose(x+.145*scale,y+.40*scale,z,swing*.72,0,0,.15*scale,.65*scale,.15*scale));parts.ls.push(compose(x-.145*scale,y+.075*scale,z-.09*direction*scale,0,0,0,.21*scale,.14*scale,.34*scale));parts.rs.push(compose(x+.145*scale,y+.075*scale,z-.09*direction*scale,0,0,0,.21*scale,.14*scale,.34*scale));cols.shadow.push(.16,.19,.24);cols.head.push(...skinColor);cols.hair.push(...hairColor);cols.le.push(.04,.05,.07);cols.re.push(.04,.05,.07);cols.body.push(...shirt);cols.hip.push(...trouser);cols.la.push(...skinColor);cols.ra.push(...skinColor);cols.ll.push(...trouser);cols.rl.push(...trouser);cols.ls.push(.96,.97,1);cols.rs.push(.96,.97,1);}const draw=(meshKey,partKey)=>this.r.drawInstances(this.meshes[meshKey],flattenMatrices(parts[partKey]),new Float32Array(cols[partKey]),f.length);draw('cylinder','shadow');draw('sphere','head');draw('sphere','hair');draw('sphere','le');draw('sphere','re');draw('box','body');draw('box','hip');draw('cylinder','la');draw('cylinder','ra');draw('cylinder','ll');draw('cylinder','rl');draw('box','ls');draw('box','rs');return f;}
  }
  const gateLabel=opt=>opt.op==='mul'?`×${opt.value}`:opt.op==='add'?`+${opt.value}`:opt.op==='sub'?`−${opt.value}`:`÷${opt.value}`;
  const isGoodGate=opt=>opt.op==='mul'||opt.op==='add';
  window.SleepRoadSystems={Renderer,compose,makeBox,makeCylinder,makeCone,makeSphere,DEG,UI,COLORS,MAX_UPGRADE,MAX_CROWD,MAX_VISIBLE_CROWD,clamp,lerp,TAU,loadSave,saveGame,RNG,AudioEngine,CrowdBatch,gateLabel,isGoodGate};
})();
