'use strict';
(() => {
  const { Renderer, compose, makeBox, makeCylinder, makeCone, makeSphere, DEG } = window.Mini3D;
  const $ = (id) => document.getElementById(id);
  const clamp = (v,a,b) => Math.max(a,Math.min(b,v));
  const lerp = (a,b,t) => a+(b-a)*t;
  const TAU = Math.PI*2;
  const UI = {
    canvas:$('game'),labels:$('worldLabels'),hud:$('hud'),menu:$('menu'),result:$('result'),fatal:$('fatal'),progressFill:$('progressFill'),moonValue:$('moonValue'),menuMoonValue:$('menuMoonValue'),crowdCount:$('crowdCount'),soundBtn:$('soundBtn'),menuSoundBtn:$('menuSoundBtn'),exitBtn:$('exitBtn'),resultMenuBtn:$('resultMenuBtn'),playBtn:$('playBtn'),nextBtn:$('nextBtn'),retryBtn:$('retryBtn'),menuLevelValue:$('menuLevelValue'),resultBanner:$('resultBanner'),resultKicker:$('resultKicker'),resultTitle:$('resultTitle'),resultCount:$('resultCount'),resultMoons:$('resultMoons'),resultMultiplier:$('resultMultiplier'),toast:$('toast'),upgradeCrowd:$('upgradeCrowd'),upgradeMagnet:$('upgradeMagnet'),upgradeIncome:$('upgradeIncome'),crowdUpgradeText:$('crowdUpgradeText'),magnetUpgradeText:$('magnetUpgradeText'),incomeUpgradeText:$('incomeUpgradeText'),crowdUpgradeCost:$('crowdUpgradeCost'),magnetUpgradeCost:$('magnetUpgradeCost'),incomeUpgradeCost:$('incomeUpgradeCost'),missionHud:$('missionHud'),missionHudText:$('missionHudText'),missionFill:$('missionFill'),menuMissionText:$('menuMissionText'),menuMissionReward:$('menuMissionReward'),resultMission:$('resultMission'),shieldHud:$('shieldHud')
  };
  const COLORS={road:[.34,.37,.44],roadStripe:[.92,.92,.82],roadEdge:[.90,.92,.96],blue:[.20,.55,.96],blueLight:[.38,.72,1],red:[.93,.20,.25],orange:[1,.40,.13],teal:[.16,.75,.67],pink:[.90,.20,.43],purple:[.28,.23,.50],gold:[1,.72,.09],navy:[.08,.10,.20],gray:[.43,.46,.54],white:[.99,.99,1],grass:[.36,.68,.40],grassDark:[.24,.51,.31],island:[.30,.44,.66],islandTop:[.45,.66,.88],step0:[.22,.76,.91],step1:[.16,.50,.94],step2:[.35,.20,.91],step3:[.67,.12,.78]};
  const SAVE_KEY='sleep-road-save-v4',LEGACY_KEYS=['sleep-road-save-v2','sleep-road-save-v1'],DEFAULT_SAVE={level:1,moons:0,sound:true,upgrades:{crowd:0,magnet:0,income:0}},MAX_UPGRADE={crowd:24,magnet:10,income:10},MAX_CROWD=999,MAX_VISIBLE_CROWD=420;
  const safeNum=(v,f=0)=>{const n=Number(v);return Number.isFinite(n)?n:f;};
  function loadSave(){try{let raw=localStorage.getItem(SAVE_KEY);if(!raw){for(const k of LEGACY_KEYS){raw=localStorage.getItem(k);if(raw)break;}}if(!raw)return JSON.parse(JSON.stringify(DEFAULT_SAVE));const d=JSON.parse(raw),u=d.upgrades||{};return{level:Math.max(1,Math.floor(safeNum(d.level,1))),moons:Math.max(0,Math.floor(safeNum(d.moons??d.coins,0))),sound:d.sound!==false,upgrades:{crowd:clamp(Math.floor(safeNum(u.crowd,0)),0,MAX_UPGRADE.crowd),magnet:clamp(Math.floor(safeNum(u.magnet,0)),0,MAX_UPGRADE.magnet),income:clamp(Math.floor(safeNum(u.income,0)),0,MAX_UPGRADE.income)}};}catch{return JSON.parse(JSON.stringify(DEFAULT_SAVE));}}
  function saveGame(s){try{localStorage.setItem(SAVE_KEY,JSON.stringify(s));}catch{}}
  class RNG{constructor(seed){this.s=(seed>>>0)||1;}next(){this.s=(Math.imul(this.s,1664525)+1013904223)>>>0;return this.s/4294967296;}range(a,b){return a+(b-a)*this.next();}int(a,b){return Math.floor(this.range(a,b+1));}pick(a){return a[Math.floor(this.next()*a.length)];}}
  class AudioEngine{constructor(enabled){this.enabled=enabled;this.ac=null;this.master=null;}ensure(){if(!this.enabled)return false;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return false;if(!this.ac){this.ac=new AC();this.master=this.ac.createGain();this.master.gain.value=.105;this.master.connect(this.ac.destination);}if(this.ac.state==='suspended')this.ac.resume().catch(()=>{});return true;}tone(f,d=.08,type='sine',gain=.055,slide=1){if(!this.ensure())return;const t=this.ac.currentTime,o=this.ac.createOscillator(),g=this.ac.createGain();o.type=type;o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(Math.max(40,f*slide),t+d);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(gain,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+d+.03);}coin(){this.tone(930,.08,'sine',.05,1.22)}good(){this.tone(450,.07,'triangle',.055,1.45);setTimeout(()=>this.tone(720,.10,'sine',.045,1.18),50)}bad(){this.tone(185,.13,'sawtooth',.045,.68)}hit(){this.tone(115,.09,'square',.04,.55)}battle(){this.tone(155,.055,'square',.025,.8)}win(){this.tone(430,.12,'triangle',.06,1.35);setTimeout(()=>this.tone(650,.15,'triangle',.055,1.25),100);setTimeout(()=>this.tone(850,.22,'sine',.05,1.12),220)}fail(){this.tone(220,.28,'triangle',.055,.5)}}
  function flattenMatrices(list){const out=new Float32Array(list.length*16);for(let i=0;i<list.length;i++)out.set(list[i],i*16);return out;}
  class CrowdBatch{
    constructor(renderer,meshes){this.r=renderer;this.meshes=meshes;}
    metrics(count){const n=Math.max(1,Math.min(Math.round(count),MAX_VISIBLE_CROWD)),cols=Math.min(16,Math.max(3,Math.ceil(Math.sqrt(n*1.05)))),spacing=Math.min(.70,9.2/Math.max(1,cols-1)),rowGap=Math.min(.62,spacing*.86);return{n,cols,spacing,rowGap,depth:(Math.ceil(n/cols)-1)*rowGap};}
    formation(count){const{n,cols,spacing,rowGap}=this.metrics(count),rows=[];for(let i=0;i<n;i++){const row=Math.floor(i/cols),rowCount=Math.min(cols,n-row*cols),col=i%cols,stagger=row%2?spacing*.10:-spacing*.10;rows.push({x:(col-(rowCount-1)/2)*spacing+stagger,z:row*rowGap,index:i});}return rows;}
    draw(count,rootX,rootZ,color,time,opts={}){
      const f=this.formation(count),scale=opts.scale||1,baseY=opts.baseY||0,direction=opts.direction||1;
      const keys=['shadow','head','hair','le','re','nose','neck','body','collar','hip','lsl','rsl','la','ra','ll','rl','ls','rs'],parts={},cols={};for(const k of keys){parts[k]=[];cols[k]=[];}
      const skin=[[1,.75,.57],[.75,.46,.31],[.95,.63,.45],[.50,.31,.23],[.86,.53,.35]],hair=[[.09,.06,.05],[.27,.14,.07],[.04,.035,.035],[.53,.30,.09],[.17,.10,.07]],enemy=opts.enemy===true;
      const shirts=enemy?[[.91,.20,.28],[.98,.32,.18],[.72,.12,.25],[.95,.39,.27]]:[[.18,.52,.96],[.12,.63,.86],[.25,.43,.88],[.20,.68,.72],[.34,.49,.94]];
      for(const q of f){
        const phase=time*7.4+q.index*.71,swing=Math.sin(phase)*.30,bob=Math.abs(Math.sin(phase))*.038,x=rootX+q.x*scale,z=rootZ+q.z*direction*scale,y=baseY+bob,skinColor=skin[q.index%skin.length],hairColor=hair[(q.index*3)%hair.length],shirtBase=shirts[(q.index*7)%shirts.length],shade=.93+(q.index%3)*.03,shirt=shirtBase.map(v=>Math.min(1,v*shade)),trouser=enemy?[.24,.07,.11]:q.index%3?[.055,.15,.32]:[.12,.12,.23],style=q.index%3,hairScale=[.39,.43,.46][style],hairHeight=[.13,.17,.19][style],accent=enemy?[1,.72,.70]:q.index%2?[.78,.92,1]:[.94,.97,1];
        parts.shadow.push(compose(x,baseY+.015,z,0,0,0,.50*scale,.022,.34*scale));parts.head.push(compose(x,y+1.67*scale,z,0,0,0,.45*scale,.49*scale,.44*scale));parts.hair.push(compose(x,y+(1.84+(hairHeight-.16)*.55)*scale,z+.025*direction,0,0,0,hairScale*scale,hairHeight*scale,hairScale*scale));parts.le.push(compose(x-.088*scale,y+1.69*scale,z-.218*direction*scale,0,0,0,.052*scale,.065*scale,.038*scale));parts.re.push(compose(x+.088*scale,y+1.69*scale,z-.218*direction*scale,0,0,0,.052*scale,.065*scale,.038*scale));parts.nose.push(compose(x,y+1.62*scale,z-.238*direction*scale,0,0,0,.045*scale,.060*scale,.045*scale));parts.neck.push(compose(x,y+1.43*scale,z,0,0,0,.20*scale,.15*scale,.19*scale));parts.body.push(compose(x,y+1.08*scale,z,0,0,0,.49*scale,.69*scale,.35*scale));parts.collar.push(compose(x,y+1.31*scale,z+.176*direction*scale,0,0,0,.25*scale,.085*scale,.025*scale));parts.hip.push(compose(x,y+.72*scale,z,0,0,0,.42*scale,.20*scale,.30*scale));parts.lsl.push(compose(x-.265*scale,y+1.24*scale,z,0,0,-.20,.22*scale,.27*scale,.25*scale));parts.rsl.push(compose(x+.265*scale,y+1.24*scale,z,0,0,.20,.22*scale,.27*scale,.25*scale));parts.la.push(compose(x-.29*scale,y+.99*scale,z,swing,0,-.07,.105*scale,.38*scale,.105*scale));parts.ra.push(compose(x+.29*scale,y+.99*scale,z,-swing,0,.07,.105*scale,.38*scale,.105*scale));parts.ll.push(compose(x-.13*scale,y+.39*scale,z,-swing*.62,0,0,.135*scale,.61*scale,.135*scale));parts.rl.push(compose(x+.13*scale,y+.39*scale,z,swing*.62,0,0,.135*scale,.61*scale,.135*scale));parts.ls.push(compose(x-.13*scale,y+.075*scale,z-.075*direction*scale,0,0,0,.19*scale,.13*scale,.30*scale));parts.rs.push(compose(x+.13*scale,y+.075*scale,z-.075*direction*scale,0,0,0,.19*scale,.13*scale,.30*scale));
        cols.shadow.push(.12,.16,.22);cols.head.push(...skinColor);cols.hair.push(...hairColor);cols.le.push(.025,.03,.045);cols.re.push(.025,.03,.045);cols.nose.push(...skinColor);cols.neck.push(...skinColor);cols.body.push(...shirt);cols.collar.push(...accent);cols.hip.push(...trouser);cols.lsl.push(...shirt);cols.rsl.push(...shirt);cols.la.push(...skinColor);cols.ra.push(...skinColor);cols.ll.push(...trouser);cols.rl.push(...trouser);cols.ls.push(.97,.98,1);cols.rs.push(.97,.98,1);
      }
      const draw=(meshKey,partKey)=>this.r.drawInstances(this.meshes[meshKey],flattenMatrices(parts[partKey]),new Float32Array(cols[partKey]),f.length);draw('cylinder','shadow');draw('sphere','head');draw('sphere','hair');draw('sphere','le');draw('sphere','re');draw('sphere','nose');draw('cylinder','neck');draw('sphere','body');draw('box','collar');draw('box','hip');draw('sphere','lsl');draw('sphere','rsl');draw('cylinder','la');draw('cylinder','ra');draw('cylinder','ll');draw('cylinder','rl');draw('box','ls');draw('box','rs');return f;
    }
  }
  const gateLabel=opt=>opt.op==='mul'?`×${opt.value}`:opt.op==='add'?`+${opt.value}`:opt.op==='sub'?`−${opt.value}`:`÷${opt.value}`;
  const isGoodGate=opt=>opt.op==='mul'||opt.op==='add';
  window.SleepRoadSystems={Renderer,compose,makeBox,makeCylinder,makeCone,makeSphere,DEG,UI,COLORS,MAX_UPGRADE,MAX_CROWD,MAX_VISIBLE_CROWD,clamp,lerp,TAU,loadSave,saveGame,RNG,AudioEngine,CrowdBatch,gateLabel,isGoodGate};
})();
